sudo: required
services:
  - docker

before_install:
  - docker build -t mdjamaddar/docker-react-project -f Dockerfile.dev .

script:
  - docker run mdjamaddar/docker-react-project npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-project"
  env: "DockerReactProject-env"
  bucket_name: "elasticbeanstalk-us-east-2-247007246246"
  bucket_path: "docker-react-project"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
