sudo: required
services:
  - docker

before_install:
  - docker build -t mdjamaddar/docker-react-project -f Dockerfile.dev .

script:
  - docker run mdjamaddar/docker-react-project npm run test -- --coverage
   
